services:
  - name: sau via-crm-backend
    type: web_service
    repo: https://github.com/brunobisogni212201-fecaf/sauvia-crm
    branch: main
    autoDeploy: false
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn src.main:app --host 0.0.0.0 --port $PORT
    rootDir: apps/backend
    envVars:
      - key: APP_ENV
        value: production
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: COGNITO_CLIENT_SECRET
        sync: false
      - key: COGNITO_CLIENT_ID
        value: "6tup0p24n1ds40c467pq30b655"
      - key: COGNITO_USER_POOL_ID
        value: "us-east-1_TAZzYtUAo"
      - key: COGNITO_CLIENT_SECRET
        value: "8chosi55qhqi8pkfv0dq465n4kebsebjokqe9mjq05b7o4r64fo"
      - key: COGNITO_DOMAIN
        value: "https://sauvia-app.auth.us-east-1.amazoncognito.com"
      - key: COGNITO_REGION
        value: "us-east-1"
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: "us-east-1"
      - key: CORS_ORIGINS
        value: "https://sauvia.qzz.io,https://sauvia-app.vercel.app,http://localhost:3000"
