from src.application.dtos.patient_dto import CreatePatientDto, PatientResponse
from src.application.ports.repositories.patient_repository import PatientRepository
from src.domain.entities.patient import Patient
from src.domain.value_objects.cpf import CPF


class CreatePatientUseCase:
    def __init__(self, patient_repo: PatientRepository):
        self._patient_repo = patient_repo

    async def execute(
        self, user_id: str, dto: CreatePatientDto
    ) -> PatientResponse:
        if dto.cpf:
            CPF(dto.cpf)  # Validates CPF, raises ValueError if invalid

        patient = Patient(
            id="",  # Generated by repository
            user_id=user_id,
            name=dto.name,
            email=dto.email,
            phone=dto.phone,
            cpf=dto.cpf,
            birth_date=dto.birth_date,
            gender=dto.gender,
            height=dto.height,
            weight=dto.weight,
            goal=dto.goal,
            medical_notes=dto.medical_notes,
            address=dto.address,
            emergency_contact=dto.emergency_contact,
        )

        saved = await self._patient_repo.save(patient)
        return PatientResponse(
            id=saved.id,
            user_id=saved.user_id,
            name=saved.name,
            email=saved.email,
            phone=saved.phone,
            cpf=saved.cpf,
            birth_date=saved.birth_date,
            gender=saved.gender,
            height=saved.height,
            weight=saved.weight,
            goal=saved.goal,
            medical_notes=saved.medical_notes,
            address=saved.address,
            emergency_contact=saved.emergency_contact,
            active=saved.active,
            created_at=saved.created_at,
            updated_at=saved.updated_at,
        )
